//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicum2020.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_ROLE> TB_ROLE { get; set; }
        public virtual DbSet<TB_CODE_GEN> TB_CODE_GEN { get; set; }
        public virtual DbSet<TB_ITEM_DESK> TB_ITEM_DESK { get; set; }
        public virtual DbSet<TB_ITEMS> TB_ITEMS { get; set; }
        public virtual DbSet<TB_SPEC> TB_SPEC { get; set; }
        public virtual DbSet<TB_SQUARE> TB_SQUARE { get; set; }
        public virtual DbSet<TB_STOC_PLACE> TB_STOC_PLACE { get; set; }
        public virtual DbSet<TB_STORAGE> TB_STORAGE { get; set; }
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
    }
}
