//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicum2020.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEMS
    {
        public int ID_ITEMS { get; set; }
        public int ID_STORAGE { get; set; }
        public int ID_SPEC { get; set; }
        public int ID_PLACE { get; set; }
        public int ID_SQUARE { get; set; }
        public Nullable<System.DateTime> DATE_PRIB { get; set; }
        public Nullable<System.DateTime> DATE_OTB { get; set; }
        public Nullable<int> PLACE_PRIB { get; set; }
        public Nullable<int> PLACE_OTB { get; set; }
    
        public virtual TB_ITEM_DESK TB_ITEM_DESK { get; set; }
        public virtual TB_STOC_PLACE TB_STOC_PLACE { get; set; }
        public virtual TB_SPEC TB_SPEC { get; set; }
        public virtual TB_SQUARE TB_SQUARE { get; set; }
        public virtual TB_STORAGE TB_STORAGE { get; set; }
    }
}
