//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicum2020.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public int ID_USERS { get; set; }
        public string U_LOGIN { get; set; }
        public string U_PASS { get; set; }
        public string U_PHONE { get; set; }
        public Nullable<int> U_ROLE { get; set; }
        public string U_NAME { get; set; }
        public string U_SURNAME { get; set; }
        public string U_MIDDLENAME { get; set; }
    
        public virtual TB_ROLE TB_ROLE { get; set; }
    }
}
